First PR
DanielGoman/Titanic pull request #2
Opened 2021-12-09 22:14 UTC by DanielGoman

It's most definitely a bug, not a feature

2021-12-10 11:15 UTC, moshenas requested changes
Good work... Don't be intimidated by the amount of remarks...We'll learn how to work correctly, with git, with project organizing and with good coding practices...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +class Preprocessor:
Not sure why you deleted `src` folder... bring it back..
Put everything (but the `main.py` script) in that folder

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +class Preprocessor:
Also, you have 3 different classes in this file, split this into 3 different files and put them in a sub-folder of `src` (lets say `preprocessing`).  Long files are less readable

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +class Preprocessor:
```suggestion
class FeatureExtractor:
```
Preprocessor is not a meaningful name of this class work... It is too general. Preprocessing also includes feature normalization, data imputation, etc.
Think of a better name..

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        self.title_mapper = {'junior': ['Miss.', 'Miss', 'Master.', 'Master'],
All this attributes are not an **instance**'s attributes. There are rather **class** attributes, they can be a class consts (defined outside of the `__init__` function.
`__init__` should contain attributes that defines an **instance** of a class and who are unique to this instance..

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        transforms = [self.cabin_transform,
Instead of making this hard coded transforms, you could make this an attribute of the class (input to `__init__`) and this way you could edit this list easily as a user...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        for func in transforms:
Great!

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +    # Split the 'Cabin' feature into 2 features - 'cabin_type' and 'cabin_indexes'
We use docstring (In our team we use Google docstring, use this one)
Read about it [here](https://realpython.com/documenting-python-code/#documenting-your-python-code-base-using-docstrings)

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +    def cabin_transform(self, df: pd.DataFrame) -> pd.DataFrame:
Notice that you don't use `self` in this function at all... i.e. you don't use the instance of the class here... It's true to all of the transforms you implemented in this class.. Read about static methods and apply it to all this transforms

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        cabins = df['Cabin'].dropna().map(lambda x: x.split(' '))
Split it to 2 different lines - dropping nan and the mapping

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            for item in passenger_cabins:
You can use list comprehension here

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        for idx, passenger_cabins in zip(cabins.index, cabins.tolist()):
Look for better way to iterate over this series without `zip(cabins.index, cabins.tolist())`

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        other = 'other'
Meaningful names... add suffix like `_label` or something..

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        grouping_type_df.loc[other_idx, 'grouping_type'] = other
You can do this with an `apply` method on the df... It would be less ugly

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        in_cabin_count_df.loc[more_than_one_in_cabin.index, 'multiple_cabins'] = 1
I'm sure there is a nicer way to do this operation... Don't have the power to look it up :) That's your job...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +    def age_groups_transform(self, df: pd.DataFrame) -> pd.DataFrame:
Where are the credits??? I feel betrayed

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            return self.other_title
Why `title_mapper` has the key `other`, if there is `self.other_title`

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +class Imputer:
Imputer of what? Meaningful names...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        super().__init__()
You don't inherit from other class, so you don't need to call `super().__init__()`

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        super().__init__()
Same as before

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        self.reg_dict = {}
Meaningful names...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        self.age_groups = ['senior', 'junior']
Class attributes

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +    def set_params(self, **params: dict) -> Imputer:
It looks like you don't use this function...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            temp_df = df[df['age_group'] == age_group].copy()
If I see `temp` in your code one more time....

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            reg = RandomForestRegressor(n_estimators=getattr(self, 'n_estimators'),
`reg` is short for regular... I don't know what you're talking about...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            reg = RandomForestRegressor(n_estimators=getattr(self, 'n_estimators'),
I saw (after checking in `main.py`, it wasn't so clear) that you initialize the random forest parameters with gridsearch... So now I understand the `set_params` function
However, for readability, I think that you should initialize these parameters in the `__init__` function and put `None` in them... and than it would be much more clear to read...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        features_to_drop = [item for item in features_to_drop]
```suggestion
        features_to_drop = list(set(X_missing.columns) - set(trained_features))
```

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        features_to_add = set(trained_features) - set(X_missing.columns)
same as before

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +            y_pred = np.ceil(regressor.predict(X_missing))
Why `ceil` and not `round`?

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +                if len(item) == 0:
You can just use `if item is None`... You basically check for an empty list... the double if is not necessary...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +    # encoded the missingness of 'cabin_type' using an additional label - 'Missing'
missingness in not a word... Abusing English is allowed only for Tzatz team members...

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +        trained_features = list(chain.from_iterable(self.trained_features.values()))
That's a very cool way to handle this... great!

2021-12-10 11:15 UTC, moshenas commented on preprocess.py
> +# TODO: choose a method for feature selection and implement it
For the future.. If there is a feature that you didn't implement yet, it shouldn't be in your PR...
When you split this classes into different files you could just not include this file in your commit...

2021-12-10 11:15 UTC, moshenas commented on model.py
> +class Model(BaseEstimator, ClassifierMixin):
Why implementing a model abstract class, if you use sklearn models where all this methods are implemented?
If you'll want to implement a model that sklearn don't have... You could implement it with this functions...

2021-12-12 11:05 UTC, DanielGoman commented on preprocess.py
> +class Preprocessor:
Created src folder and moved preprocessor.py, mode.py into it.

2021-12-12 11:09 UTC, DanielGoman commented on preprocess.py
> +class Preprocessor:
I split preprocessor.py into 3 files

2021-12-12 11:12 UTC, DanielGoman commented on preprocess.py
> +class Preprocessor:
changed the class and file names to FeatureExtractor, sounds better than FeatureEngineering

2021-12-12 13:10 UTC, DanielGoman commented on preprocess.py
> +        self.title_mapper = {'junior': ['Miss.', 'Miss', 'Master.', 'Master'],
moved class attributes outside of the `__init__`

2021-12-12 13:10 UTC, DanielGoman commented on preprocess.py
> +        for func in transforms:
Indeed I am

2021-12-12 13:12 UTC, DanielGoman commented on preprocess.py
> +    def cabin_transform(self, df: pd.DataFrame) -> pd.DataFrame:
changed all functions that do not use `self` to static

2021-12-12 13:13 UTC, DanielGoman commented on preprocess.py
> +        cabins = df['Cabin'].dropna().map(lambda x: x.split(' '))
done

2021-12-12 13:13 UTC, DanielGoman commented on preprocess.py
> +            for item in passenger_cabins:
replaced with list comprehension

2021-12-12 13:16 UTC, DanielGoman commented on preprocess.py
> +        for idx, passenger_cabins in zip(cabins.index, cabins.tolist()):
Used `cabins.iteritems()` instead

2021-12-12 13:17 UTC, DanielGoman commented on preprocess.py
> +        other = 'other'
added

2021-12-12 13:40 UTC, DanielGoman commented on preprocess.py
> +    def age_groups_transform(self, df: pd.DataFrame) -> pd.DataFrame:
Dear lord don't make me spell out your last surname in English

2021-12-12 13:42 UTC, DanielGoman commented on preprocess.py
> +            return self.other_title
removed `'other'` key

2021-12-12 13:42 UTC, DanielGoman commented on preprocess.py
> +class Imputer:
changed to MissingFeaturesImputer

2021-12-12 13:44 UTC, DanielGoman commented on preprocess.py
> +        super().__init__()
removed `super().__init()` calls from `FeatureExtractor, MissingFeatureImputer, SelectKBest`

2021-12-12 13:46 UTC, DanielGoman commented on preprocess.py
> +        super().__init__()
removed the call to `super().__init__()`

2021-12-12 13:57 UTC, DanielGoman commented on preprocess.py
> +        self.reg_dict = {}
renamed to `regressors_dict`

2021-12-12 13:57 UTC, DanielGoman commented on preprocess.py
> +        self.age_groups = ['senior', 'junior']
moved outside of the `__init__`

2021-12-12 14:01 UTC, DanielGoman commented on preprocess.py
> +            temp_df = df[df['age_group'] == age_group].copy()
you shall not

2021-12-12 14:01 UTC, DanielGoman commented on preprocess.py
> +            reg = RandomForestRegressor(n_estimators=getattr(self, 'n_estimators'),
renamed to `'regressor'`

2021-12-12 14:05 UTC, DanielGoman commented on preprocess.py
> +            reg = RandomForestRegressor(n_estimators=getattr(self, 'n_estimators'),
added `n_estimators, max_depth` initialization inside the `__init__` of `MissingFeaturesImputer`

2021-12-12 14:07 UTC, DanielGoman commented on preprocess.py
> +        features_to_drop = [item for item in features_to_drop]
awkward, lets just ignore these 2 lines

2021-12-13 08:58 UTC, merged